# Generated by Django 4.2.7 on 2024-04-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210322_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigIntegerField( primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
